USB_VID = 0x2341
USB_PID = 0x824D
USB_PRODUCT = "SAMD21 M0 Mini"
USB_MANUFACTURER = "Unbranded"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

SUPEROPT_GC = 0
